const fs = require('fs');
let data = fs.readFileSync('src/views/chef/inventory/index.tsx', 'utf8');

const targetStr =                               <div className=\"flex flex-col gap-1 w-32 mx-auto md:mx-0\">\n                                <span className={\ont-black text-center md:text-left \\}>\n                                  {Number(ing.stock).toFixed(ing.unit === \"kg\" ? 1 : 0)} {ing.unit}\n                              )}\n                            </td>\n                            <td className=\"px-5 py-4 text-right\">\n                                  title={isExpanded ? \"Ðóng danh sách lô\" : \"Xem chi ti?t lô\"}\n                                >\n                                  {isExpanded ? <Minus size={10} /> : <Eye size={10} />}\n                                  {isExpanded ? \"Ðóng Lô\" : \"Xem Lô\"}\n                                </button>\n                              </div>\n                            </td>;

const replaceStr =                               <div className=\"flex flex-col gap-1 w-32 mx-auto md:mx-0\">\n                                <span className={\ont-black text-center md:text-left \\}>\n                                  {Number(ing.stock).toFixed(ing.unit === \"kg\" ? 1 : 0)} {ing.unit}\n                                </span>\n                                <div className=\"w-full bg-slate-100 rounded-full h-1.5 border border-slate-200/50\">\n                                  <div\n                                    className={\h-full rounded-full \\}\n                                    style={{ width: \\%\ }}\n                                  />\n                                </div>\n                              </div>\n                            </td>\n                            <td className=\"px-5 py-4 text-center\">\n                              {isLow ? (\n                                <span className=\"inline-flex items-center gap-1 text-[9px] font-black text-rose-700 bg-rose-100 px-2 py-0.5 rounded border border-rose-250 animate-pulse\">\n                                  <AlertTriangle size={10} /> T?N TH?P (Du?i {ing.threshold} {ing.unit})\n                                </span>\n                              ) : (\n                                <span className=\"inline-flex items-center gap-1 text-[9px] font-black text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-250\">\n                                  <Check size={10} /> AN TOÀN\n                                </span>\n                              )}\n                            </td>\n                            <td className=\"px-5 py-4 text-right\">\n                              <div className=\"flex justify-end\">\n                                <button\n                                  onClick={(e) => {\n                                    e.stopPropagation();\n                                    toggleRowExpansion(ing.id);\n                                  }}\n                                  className=\"flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 text-blue-700 hover:bg-blue-100 rounded-lg text-[10px] font-black uppercase tracking-wider transition-colors\"\n                                  title={isExpanded ? \"Ðóng danh sách lô\" : \"Xem chi ti?t lô\"}\n                                >\n                                  {isExpanded ? <Minus size={10} /> : <Eye size={10} />}\n                                  {isExpanded ? \"Ðóng Lô\" : \"Xem Lô\"}\n                                </button>\n                              </div>\n                            </td>;

data = data.replace(targetStr, replaceStr);
fs.writeFileSync('src/views/chef/inventory/index.tsx', data, 'utf8');
