import { GoogleGenerativeAI } from "@google/generative-ai";

export interface ParsedBookingIntent {
  party_size?: number | null;
  booking_date?: string | null; // YYYY-MM-DD
  booking_time?: string | null; // HH:mm (24h)
  area_preference?: string | null; // "Tầng 1" | "Tầng 2" | "Sân vườn" | null
  guest_name?: string | null;
  guest_phone?: string | null;
  guest_email?: string | null;
  is_complete: boolean; // true if party_size, booking_date, and booking_time are all present and valid
  missing_fields: string[]; // List of fields that are still needed (e.g. ["party_size", "booking_time"])
  reply_prompt: string; // Friendly Vietnamese reply generated by AI to guide customer
}

/**
 * Uses Google Gemini AI to extract structured booking parameters from natural Vietnamese conversation.
 * Handles relative date expressions ("tối mai", "thứ 7 tuần này", "ngày 15 tháng này") and relative times ("7h tối", "hai giờ chiều").
 */
export const parseBookingIntentWithAI = async (
  conversationHistory: { role: "user" | "model"; text: string }[],
  latestUserText: string,
): Promise<ParsedBookingIntent | null> => {
  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    console.warn("⚠️ No GEMINI_API_KEY found in .env");
    return null;
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    // Models to try in order of preference
    const modelNames = ["gemini-2.0-flash", "gemini-2.5-flash", "gemini-1.5-pro", "gemini-pro"];
    let model;
    for (const name of modelNames) {
      try {
        model = genAI.getGenerativeModel({ model: name });
        break;
      } catch (e) {
        // try next
      }
    }
    if (!model) {
      model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
    }

    const now = new Date();
    // Format Vietnam time (UTC+7)
    const options: Intl.DateTimeFormatOptions = {
      timeZone: "Asia/Ho_Chi_Minh",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      weekday: "long",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    };
    const currentDateTimeStr = new Intl.DateTimeFormat("vi-VN", options).format(now);

    const systemPrompt = `Bạn là Trợ lý AI lễ tân thông minh của nhà hàng cao cấp ResManager.
Hôm nay là: ${currentDateTimeStr}. (Dùng mốc thời gian này để tính toán các từ tương đối như "hôm nay", "tối mai", "trưa mai", "thứ 7 tuần này", "ngày mai", v.v.)

THÔNG TIN VÀ QUY ĐỊNH NHÀ HÀNG RESMANAGER:
- Giờ mở cửa nhà hàng: 09:00 - 22:00 hằng ngày.
- QUY ĐỊNH ĐẶT BÀN TRỰC TUYẾN/ONLINE: Nhà hàng CHỈ nhận đặt bàn trực tuyến trước 19:00 tối (khung giờ từ 10:00 đến 19:00). Sau 19:00 (từ 19:01 đến 22:00) hệ thống online ngưng nhận đặt bàn, khách cần đến trực tiếp nhà hàng hoặc gọi Hotline.
- Nếu khách muốn đặt bàn khung giờ SAU 19:00 (ví dụ: 19:30, 20:00, 20:30, 21:00), hãy nhắc khách nhẹ nhàng trong reply_prompt: "Dạ theo quy định nhà hàng, hệ thống chỉ nhận đặt bàn trực tuyến trước 19:00 tối ạ. Khung giờ đó anh/chị vui lòng đến trực tiếp nhà hàng hoặc liên hệ Hotline 028 3829 4000 để được hỗ trợ xếp bàn ạ!" và đặt is_complete: false, booking_time: null.
- Địa chỉ/Khu vực: Tầng 1, Tầng 2, Sân vườn ngoài trời thoáng mát. Có bãi đỗ xe ô tô và xe máy miễn phí.
- Thực đơn: Phục vụ các món Việt Nam, Hải sản, Bò lúc lắc, Lẩu (Lẩu Thái, Lẩu Nấm), Đồ uống phong phú.
- Hotline: 028 3829 4000.

NHIỆM VỤ CỦA BẠN:
1. Trả lời BẤT KỲ câu hỏi nào của khách một cách tự nhiên, lịch sự, thân thiện như ChatGPT/Gemini (hỏi giờ mở cửa, hỏi thực đơn, hỏi gửi xe, hỏi đặt bàn, chát linh tinh).
2. Đồng thời trích xuất các thông tin đặt bàn (nếu có trong hội thoại) thành khối JSON bên dưới.

YÊU CẦU ĐẦU RA (DUY NHẤT KHỐI JSON):
\`\`\`json
{
  "party_size": number | null,        // Số lượng khách (ví dụ: 4). Giữ nguyên số lượng từ hội thoại trừ khi khách muốn đổi.
  "booking_date": string | null,      // YYYY-MM-DD.
  "booking_time": string | null,      // 24h HH:mm (ví dụ: "19:00").
  "area_preference": string | null,   // "Tầng 1", "Tầng 2", "Sân vườn" hoặc null.
  "guest_name": string | null,        // Tên khách nếu khách cung cấp hoặc xưng tên.
  "guest_phone": string | null,       // Số điện thoại nếu khách gõ SĐT.
  "is_complete": boolean,             // true NẾU VÀ CHỈ NẾU đã có đủ: party_size, booking_date, booking_time.
  "reply_prompt": string              // CÂU TRẢ LỜI CỦA AI DÀNH CHỐ KHÁCH. Nếu khách hỏi câu hỏi chung (ví dụ: "nhà hàng mở cửa mấy giờ"), hãy trả lời chính xác câu hỏi đó! Không được ép khách nhập tên/SĐT nếu khách chỉ đang hỏi câu hỏi thông tin!
}
\`\`\`

LƯU Ý CỰC KỲ QUAN TRỌNG:
- Trả về DUY NHẤT một khối JSON.
- reply_prompt là lời thoại thực sự của AI gửi cho khách. Hãy trả lời cực kỳ thông minh, tự nhiên theo đúng câu hỏi của khách!`;

    const chatMessages = conversationHistory.map((msg) => `${msg.role === "user" ? "Khách" : "AI"}: ${msg.text}`).join("\n");
    const fullPrompt = `${systemPrompt}\n\nLỊCH SỬ HỘI THOẠI TRƯỚC ĐÓ:\n${chatMessages}\n\nTIN NHẮN MỚI NHẤT CỦA KHÁCH: "${latestUserText}"\n\nJSON KẾT QUẢ:`;
    const candidateModels = ["gemini-3.6-flash", "gemini-3.5-flash", "gemini-flash-latest"];
    let responseText = "";
    let lastErrorMsg = "";

    for (const modelName of candidateModels) {
      try {
        const m = genAI.getGenerativeModel({ model: modelName });
        const result = await m.generateContent(fullPrompt);
        responseText = result.response.text().trim();
        if (responseText) break;
      } catch (err: any) {
        lastErrorMsg = err.message || String(err);
      }
    }

    if (!responseText) {
      console.warn(`⚠️ Tất cả các Gemini models đều thất bại. Lỗi cuối cùng:`, lastErrorMsg);
      return null;
    }

    // Clean JSON markdown wrapping if present
    const cleanJsonStr = responseText.replace(/```json/gi, "").replace(/```/g, "").trim();
    const parsedData: ParsedBookingIntent = JSON.parse(cleanJsonStr);

    return parsedData;
  } catch (error) {
    console.error("❌ Lỗi khi phân tích intent đặt bàn bằng AI (Gemini):", error);
    return null;
  }
};
